name: Deployment

on:
  push:
    branches: [main]

jobs:
  style:
    name: Deploy
    runs-on: ubuntu-latest

    steps :
    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      run : npm ci

    - name: Build application
      run : npm run build

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Setup Gcloud
      run: gcloud builds submit --tag us-central1-docker.pkg.dev/peak-text-506103-v3/notely-ar-repo/notely