name: Deployment

on:
  push:
    branches: [main]

jobs:
  style:
    name: Deploy
    runs-on: ubuntu-latest

    steps :
    - name: Check out code
      uses: actions/checkout@v6

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      run : npm ci

    - name: Build application
      run : npm run build

    - name: Setup Gcloud
      run: gcloud init

    - name: Setup Gcloud
      run: gcloud builds submit --tag us-central1-docker.pkg.dev/peak-text-506103-v3/notely-ar-repo/notely